
services:
  db:
    container_name: movie-time-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: movie_time
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_PASSWORD: secret-pw
    expose:
      - "3306"
    volumes:
     - ./movie-time-backend/migrations/tables.sql:/docker-entrypoint-initdb.d/0_init.sql
    # command: --init-file=/movie-time-backend/migrations/tables.sql
    networks:
      - backend

  backend:
    depends_on:
        - db
    build: ./movie-time-backend
    container_name: movie-time-backend
    ports:
      - "3001:3001"
    volumes:
      - ./movie-time-backend:/usr/src/app
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret-pw
    command: ["npm", "run", "start"]
    networks:
      - backend

networks:
  backend:
    driver: bridge
