
services:
  db:
    container_name: movie-time-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: movie_time
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_PASSWORD: secret-pw
    expose:
      - "3306"
    volumes:
      - movie-time-volume:/var/lib/mysql
    networks:
      - backend

  backend:
    depends_on:
        - db
    build: ./movie-time-backend
    container_name: movie-time-backend
    ports:
      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - ./movie-time-backend:/usr/src/app
    environment:
      - NODE_ENV=staging
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret-pw
      - MYSQL_DATABASE=movie_time
      - TMDB_API_URL=https://api.themoviedb.org/3
    command: ["npm", "run", "start"]
    networks:
      - backend
  client:
    depends_on:
        - backend
    build: ./movie-time-client
    container_name: movie-time-client
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - API_URL=backend
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  movie-time-volume:
